blueprints/empresas.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required 
from database import get_db_connection

empresas_bp = Blueprint('empresas_bp', __name__)


@empresas_bp.route('/empresas', methods=['GET'])
@login_required
def listar_empresas():
    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        cursor.execute("""
            SELECT ID_Entidad, Rut, Nombre, FonoMovil, Email
            FROM EntidadComercial
            WHERE TipoEntidad = 'Empresa'
            ORDER BY Nombre ASC
            """)
        empresas = cursor.fetchall()

    except Exception as e:
        flash(f"Error al obtener los datos de las empresas: {e}", "error")
        empresas = []

    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

    return render_template('configuracion/empresas/empresas.html', empresas=empresas)

@empresas_bp.route('/empresas/add', methods=['GET', 'POST'])
@login_required
def add_empresa():
    if request.method == 'POST':
        rut = request.form['rut']
        nombre = request.form['nombre'].upper()
        fono_fijo = request.form['fono_fijo']
        fono_movil = request.form['fono_movil']
        email = request.form['email']

        try:
            conn = get_db_connection()
            cursor = conn.cursor()

            cursor.execute("""
                INSERT INTO EntidadComercial (Rut, Nombre, FonoFijo, FonoMovil, Email, TipoEntidad)
                VALUES (%s, %s, %s, %s, %s, 'Empresa')
            """, (rut, nombre, fono_fijo, fono_movil, email))
            conn.commit()

            flash("Empresa agregada exitosamente.", "success")
            return redirect(url_for('empresas_bp.listar_empresas'))
        except Exception as e:
            conn.rollback()
            flash(f"Error al agregar la empresa: {e}", "error")
        finally:
            cursor.close()
            conn.close()

    return render_template('configuracion/empresas/add_empresas.html')

@empresas_bp.route('/delete_empresa/<int:id_empresa>', methods=['POST'])
@login_required
def delete_empresa(id_empresa):
    print(f"Entrando a delete_empresa con ID: {id_empresa}")
    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        cursor.execute("SELECT * FROM EntidadComercial WHERE ID_Entidad = %s AND TipoEntidad = 'Empresa'", (id_empresa,))
        empresa = cursor.fetchone()
        if not empresa:
            flash("La empresa no existe o no es del tipo 'Banco'.", "error")
            return redirect(url_for('listar_empresas'))

        cursor.execute("DELETE FROM EntidadComercial WHERE ID_Entidad = %s AND TipoEntidad = 'Empresa'", (id_empresa,))
        conn.commit()

        print(f"Empresa eliminada: {id_empresa}")
        flash("Empresa eliminada exitosamente.", "success")
    except Exception as e:
        conn.rollback()
        print(f"Error al eliminar: {e}")
        flash(f"Error al eliminar la empresa: {e}", "error")
    finally:
        cursor.close()
        conn.close()

    return redirect(url_for('empresas_bp.listar_empresas'))

@empresas_bp.route('/empresas/edit/<int:id_empresa>', methods=['GET', 'POST'])
@login_required
def edit_empresa(id_empresa):
    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        if request.method == 'POST':
            rut = request.form['rut']
            nombre = request.form['nombre']
            email = request.form.get('email') 
            fono_fijo = request.form.get('fono_fijo')  
            fono_movil = request.form.get('fono_movil')  

            cursor.execute("""
                UPDATE EntidadComercial
                SET Rut = %s, Nombre = %s, Email = %s, FonoFijo = %s, FonoMovil = %s
                WHERE ID_Entidad = %s AND TipoEntidad = 'Empresa'
            """, (rut, nombre, email, fono_fijo, fono_movil, id_empresa))
            conn.commit()

            flash("Empresa actualizado exitosamente.", "success")
            return redirect(url_for('empresas_bp.listar_empresas'))

        cursor.execute("""
            SELECT Rut, Nombre, Email, FonoFijo, FonoMovil
            FROM EntidadComercial
            WHERE ID_Entidad = %s AND TipoEntidad = 'Empresa'
        """, (id_empresa,))
        empresa = cursor.fetchone()

        if not empresa:
            flash("Empresa no encontrada.", "error")
            return redirect(url_for('empresas_bp.listar_empresas'))

    except Exception as e:
        if conn:
            conn.rollback()
        flash(f"Error al procesar la solicitud: {e}", "error")
        return redirect(url_for('empresas_bp.listar_empresas'))
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

    return render_template('configuracion/empresas/edit_empresa.html', empresa=empresa, id_empresa=id_empresa)

templates/configuracion/empresas/add_empresas.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Agregar Empresa</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles.css') }}"
    />
  </head>
  <body class="centered-form">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Sistema de Inversiones</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto">
            <!-- Menú Desplegable -->
            <li class="nav-item dropdown mx-3">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Ingresos
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/bancos">Bancos</a></li>
                <li><a class="dropdown-item" href="/empresas">Empresas</a></li>
                <li><a class="dropdown-item" href="/corredores">Corredores de Bolsa</a></li>
                <li><a class="dropdown-item" href="/companias">Compañías de Seguro</a></li>
                <li><a class="dropdown-item" href="/clientes">Clientes</a></li>
                <li><a class="dropdown-item" href="/parametros">Parámetros</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown mx-3">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Inversiones
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/acciones">Acciones</a></li>
                <li><a class="dropdown-item" href="/fondos_mutuos">FFMM</a></li>
                <li><a class="dropdown-item" href="/deposito_a_plazo">DP</a></li>
              </ul>
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link" href="/boletas_garantia"
                >Boletas de Garantia</a
              >
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link" href="/polizas">Polizas de Seguro</a>
            </li>
          </ul>
          <!-- Enlace al lado derecho -->
          </ul>
          <!-- Enlace al lado derecho -->
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link" href="/logout">Cerrar Sesión</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <form action="{{ url_for('empresas_bp.add_empresa') }}" method="POST">
      <h1>Agregar Empresa</h1>
      <label for="rut">Rut:</label>
      <input
        type="text"
        id="rut"
        name="rut"
        oninput="this.value = this.value.replace(/[^0-9]/g, '');"
        required
      /><br /><br />

      <label for="nombre">Nombre:</label>
      <input
        type="text"
        id="nombre"
        name="nombre"
        oninput="this.value = this.value.toUpperCase()"
        required
      /><br /><br />

      <label for="fono_fijo">Fono Fijo:</label>
      <input
        type="text"
        id="fono_fijo"
        name="fono_fijo"
        oninput="this.value = this.value.replace(/[^0-9]/g, '');"
        required
      /><br /><br />

      <label for="fono_movil">Fono Movil:</label>
      <input
        type="text"
        id="fono_movil"
        name="fono_movil"
        oninput="this.value = this.value.replace(/[^0-9]/g, '');"
        required
      /><br /><br />

      <label for="email">E-mail:</label>
      <input type="text" id="email" name="email" required /><br /><br />

      <button type="submit">Guardar</button>
      <button onclick="location.href='/empresas'" type="button">Volver</button>
    </form>
  </body>
</html>

templates/configuracion/empresas/edit_empresa.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Editar Empresa</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles.css') }}"
    />
  </head>
  <body class="centered-form">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Sistema de Inversiones</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto">
            <!-- Menú Desplegable -->
            <li class="nav-item dropdown mx-3">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Ingresos
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/bancos">Bancos</a></li>
                <li><a class="dropdown-item" href="/empresas">Empresas</a></li>
                <li><a class="dropdown-item" href="/corredores">Corredores de Bolsa</a></li>
                <li><a class="dropdown-item" href="/companias">Compañías de Seguro</a></li>
                <li><a class="dropdown-item" href="/clientes">Clientes</a></li>
                <li><a class="dropdown-item" href="/parametros">Parámetros</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown mx-3">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Inversiones
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/acciones">Acciones</a></li>
                <li><a class="dropdown-item" href="/fondos_mutuos">FFMM</a></li>
                <li><a class="dropdown-item" href="/deposito_a_plazo">DP</a></li>
              </ul>
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link" href="/boletas_garantia"
                >Boletas de Garantia</a
              >
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link" href="/polizas">Polizas de Seguro</a>
            </li>
          </ul>
          <!-- Enlace al lado derecho -->
          </ul>
          <!-- Enlace al lado derecho -->
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link" href="/logout">Cerrar Sesión</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <form
      action="{{ url_for('empresas_bp.edit_empresa', id_empresa=id_empresa) }}"
      method="POST"
    >
      <h1>Editar Empresa</h1>
      <label for="rut">Rut:</label>
      <input
        type="text"
        id="rut"
        name="rut"
        value="{{ empresa[0] }}"
        required
      /><br /><br />

      <label for="nombre">Nombre:</label>
      <input
        type="text"
        id="nombre"
        name="nombre"
        value="{{ empresa[1] }}"
        required
      /><br /><br />

      <label for="email">Email:</label>
      <input
        type="email"
        id="email"
        name="email"
        value="{{ empresa[2] }}"
      /><br /><br />

      <label for="fono_fijo">Fono Fijo:</label>
      <input
        type="text"
        id="fono_fijo"
        name="fono_fijo"
        value="{{ empresa[3] }}"
        oninput="this.value = this.value.replace(/[^0-9]/g, '');"
      /><br /><br />

      <label for="fono_movil">Fono Móvil:</label>
      <input
        type="text"
        id="fono_movil"
        name="fono_movil"
        value="{{ empresa[4] }}"
        oninput="this.value = this.value.replace(/[^0-9]/g, '');"
      /><br /><br />

      <button type="submit">Guardar Cambios</button>
      <button type="button" onclick="location.href='/empresas'">Volver</button>
    </form>
  </body>
</html>

templates/configuracion/empresas/empresas.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Listado de Empresas</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      rel="stylesheet"
    />
    <link
      rel="icon"
      href="{{ url_for('static', filename='images/favicon.png') }}"
      type="image/x-icon"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      defer
    ></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Sistema de Inversiones</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto">
            <!-- Menú Desplegable -->
            <li class="nav-item dropdown mx-3">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Ingresos
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/bancos">Bancos</a></li>
                <li><a class="dropdown-item" href="/empresas">Empresas</a></li>
                <li><a class="dropdown-item" href="/corredores">Corredores de Bolsa</a></li>
                <li><a class="dropdown-item" href="/companias">Compañías de Seguro</a></li>
                <li><a class="dropdown-item" href="/clientes">Clientes</a></li>
                <li><a class="dropdown-item" href="/parametros">Parámetros</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown mx-3">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Inversiones
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/acciones">Acciones</a></li>
                <li><a class="dropdown-item" href="/fondos_mutuos">FFMM</a></li>
                <li><a class="dropdown-item" href="/deposito_a_plazo">DP</a></li>
              </ul>
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link" href="/boletas_garantia"
                >Boletas de Garantia</a
              >
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link" href="/polizas">Polizas de Seguro</a>
            </li>
          </ul>
          <!-- Enlace al lado derecho -->
          </ul>
          <!-- Enlace al lado derecho -->
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link" href="/logout">Cerrar Sesión</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <h1 class="ms-3">Empresas</h1>

    <!-- Botón para agregar un nuevo banco -->
    <a href="/empresas/add"><button class="btn btn-primary ms-3">Agregar Empresas</button></a>

    <br /><br />

    <!-- Tabla de bancos -->
    <table class="table table-dark table-striped">
      <thead>
        <tr class="text-center">
          <th scope="col">ID</th>
          <th scope="col">Rut</th>
          <th scope="col">Nombre</th>
          <th scope="col">Fono Movil</th>
          <th scope="col">Email</th>
          <th scope="col">Acciones</th>
        </tr>
      </thead>
      <tbody>
        {% for empresa in empresas %}
        <tr class="text-center">
          <td>{{ empresa[0] }}</td>
          <td>{{ empresa[1] }}</td>
          <td>{{ empresa[2] }}</td>
          <td>{{ empresa[3] }}</td>
          <td>{{ empresa[4] }}</td>
          <td>
            <!-- Botón para editar -->
            <a href="/empresas/edit/{{ empresa[0] }}"
              ><button class="btn btn-warning">Editar</button></a
            >

            <!-- Botón para eliminar -->
            <form
              action="{{ url_for('empresas_bp.delete_empresa', id_empresa=empresa[0]) }}"
              method="POST"
              style="display: inline"
              onsubmit="return confirm('¿Estás seguro de que deseas eliminar esta empresa?');"
            >
              <button type="submit" class="btn btn-danger">
                Eliminar
              </button>
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <br />
    <a href="/"><button class="btn btn-primary ms-3">Volver al Inicio</button></a>
  </body>
</html>