blueprints/bancos.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required 
from database import get_db_connection

bancos_bp = Blueprint('bancos_bp', __name__)

@bancos_bp.route('/bancos', methods=['GET'])
@login_required
def listar_bancos():
    try:
 
        conn = get_db_connection()
        cursor = conn.cursor()

        cursor.execute("""
            SELECT ID_Entidad, Rut, Nombre, FonoMovil, Email
            FROM Entidad
            WHERE TipoEntidad = 'Banco'
            ORDER BY Nombre ASC
            """)
        bancos = cursor.fetchall()

    except Exception as e:
        flash(f"Error al obtener los datos de los bancos: {e}", "error")
        bancos = []

    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

    return render_template('configuracion/bancos/bancos.html', bancos=bancos)

@bancos_bp.route('/delete_banco/<int:id_banco>', methods=['POST'])
@login_required
def delete_banco(id_banco):
    print(f"Entrando a delete_banco con ID: {id_banco}")
    try:

        conn = get_db_connection()
        cursor = conn.cursor()

        cursor.execute("SELECT * FROM Entidad WHERE ID_Entidad = %s AND TipoEntidad = 'Banco'", (id_banco,))
        banco = cursor.fetchone()
        if not banco:
            flash("El banco no existe o no es del tipo 'Banco'.", "error")
            return redirect(url_for('listar_bancos'))

        cursor.execute("DELETE FROM Entidad WHERE ID_Entidad = %s AND TipoEntidad = 'Banco'", (id_banco,))
        conn.commit()

        print(f"Banco eliminado: {id_banco}")
        flash("Banco eliminado exitosamente.", "success")

    except Exception as e:
        conn.rollback()
        print(f"Error al eliminar: {e}")
        flash(f"Error al eliminar el banco: {e}", "error")
    finally:
        cursor.close()
        conn.close()

    return redirect(url_for('bancos_bp.listar_bancos'))

@bancos_bp.route('/bancos/add', methods=['GET', 'POST'])
@login_required
def add_banco():
    if request.method == 'POST':
        rut = request.form['rut']
        nombre = request.form['nombre'].upper()
        email = request.form.get('email')  
        fono_fijo = request.form.get('fono_fijo')  
        fono_movil = request.form.get('fono_movil') 

        try:

            conn = get_db_connection()
            cursor = conn.cursor()

            cursor.execute("""
                INSERT INTO Entidad (Rut, Nombre, Email, FonoFijo, FonoMovil, TipoEntidad)
                VALUES (%s, %s, %s, %s, %s, 'Banco')
            """, (rut, nombre, email, fono_fijo, fono_movil))
            conn.commit()

            flash("Banco agregado exitosamente.", "success")
            return redirect(url_for('bancos_bp.listar_bancos'))
        except Exception as e:
            conn.rollback()
            flash(f"Error al agregar el banco: {e}", "error")
        finally:
            cursor.close()
            conn.close()

    return render_template('configuracion/bancos/add_bancos.html')

@bancos_bp.route('/bancos/edit/<int:id_banco>', methods=['GET', 'POST'])
@login_required
def edit_banco(id_banco):
    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        if request.method == 'POST':
            rut = request.form['rut']
            nombre = request.form['nombre']
            email = request.form.get('email') 
            fono_fijo = request.form.get('fono_fijo')  
            fono_movil = request.form.get('fono_movil')  

            cursor.execute("""
                UPDATE Entidad
                SET Rut = %s, Nombre = %s, Email = %s, FonoFijo = %s, FonoMovil = %s
                WHERE ID_Entidad = %s AND TipoEntidad = 'Banco'
            """, (rut, nombre, email, fono_fijo, fono_movil, id_banco))
            conn.commit()

            flash("Banco actualizado exitosamente.", "success")
            return redirect(url_for('bancos_bp.listar_bancos'))

        cursor.execute("""
            SELECT Rut, Nombre, Email, FonoFijo, FonoMovil
            FROM Entidad
            WHERE ID_Entidad = %s AND TipoEntidad = 'Banco'
        """, (id_banco,))
        banco = cursor.fetchone()

        if not banco:
            flash("Banco no encontrado.", "error")
            return redirect(url_for('bancos_bp.listar_bancos'))

    except Exception as e:
        if conn:
            conn.rollback()
        flash(f"Error al procesar la solicitud: {e}", "error")
        return redirect(url_for('bancos_bp.listar_bancos'))
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

    return render_template('configuracion/bancos/edit_banco.html', banco=banco, id_banco=id_banco)

templates/configuracion/bancos/add_bancos.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Agregar Banco</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles.css') }}"
    />
  </head>
  <body class="centered-form">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Sistema de Inversiones</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto">
            <!-- Menú Desplegable -->
            <li class="nav-item dropdown mx-3">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Ingresos
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/bancos">Bancos</a></li>
                <li><a class="dropdown-item" href="/empresas">Empresas</a></li>
                <li><a class="dropdown-item" href="/corredores">Corredores de Bolsa</a></li>
                <li><a class="dropdown-item" href="/companias">Compañías de Seguro</a></li>
                <li><a class="dropdown-item" href="/clientes">Clientes</a></li>
                <li><a class="dropdown-item" href="/parametros">Parámetros</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown mx-3">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Inversiones
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/acciones">Acciones</a></li>
                <li><a class="dropdown-item" href="/fondos_mutuos">FFMM</a></li>
                <li><a class="dropdown-item" href="/deposito_a_plazo">DP</a></li>
              </ul>
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link" href="/boletas_garantia"
                >Boletas de Garantia</a
              >
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link" href="/polizas">Polizas de Seguro</a>
            </li>
          </ul>
          <!-- Enlace al lado derecho -->
          </ul>
          <!-- Enlace al lado derecho -->
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link" href="/logout">Cerrar Sesión</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <form action="{{ url_for('bancos_bp.add_banco') }}" method="POST">
      <h1>Agregar Banco</h1>
      <label for="rut">Rut:</label>
      <input
        type="text"
        id="rut"
        name="rut"
        oninput="this.value = this.value.replace(/[^0-9]/g, '');"
        required
      /><br /><br />

      <label for="nombre">Nombre:</label>
      <input
        type="text"
        id="nombre"
        name="nombre"
        oninput="this.value = this.value.toUpperCase()"
        required
      /><br /><br />

      <label for="email">Email:</label>
      <input type="email" id="email" name="email" /><br /><br />

      <label for="fono_fijo">Fono Fijo:</label>
      <input
        type="text"
        id="fono_fijo"
        name="fono_fijo"
        oninput="this.value = this.value.replace(/[^0-9]/g, '');"
      /><br /><br />

      <label for="fono_movil">Fono Móvil:</label>
      <input
        type="text"
        id="fono_movil"
        name="fono_movil"
        oninput="this.value = this.value.replace(/[^0-9]/g, '');"
      /><br /><br />

      <button type="submit">Guardar</button>
      <button onclick="location.href='/bancos'" type="button">Volver</button>
    </form>
  </body>
</html>

templates/configuracion/bancos/bancos.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Bancos</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      rel="stylesheet"
    />
    <link
      rel="icon"
      href="{{ url_for('static', filename='images/favicon.png') }}"
      type="image/x-icon"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      defer
    ></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Sistema de Inversiones</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto">
            <!-- Menú Desplegable -->
            <li class="nav-item dropdown mx-3">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Ingresos
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/bancos">Bancos</a></li>
                <li><a class="dropdown-item" href="/empresas">Empresas</a></li>
                <li><a class="dropdown-item" href="/corredores">Corredores de Bolsa</a></li>
                <li><a class="dropdown-item" href="/companias">Compañías de Seguro</a></li>
                <li><a class="dropdown-item" href="/clientes">Clientes</a></li>
                <li><a class="dropdown-item" href="/parametros">Parámetros</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown mx-3">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Inversiones
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/acciones">Acciones</a></li>
                <li><a class="dropdown-item" href="/fondos_mutuos">FFMM</a></li>
                <li><a class="dropdown-item" href="/deposito_a_plazo">DP</a></li>
              </ul>
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link" href="/boletas_garantia"
                >Boletas de Garantia</a
              >
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link" href="/polizas">Polizas de Seguro</a>
            </li>
          </ul>
          <!-- Enlace al lado derecho -->
          </ul>
          <!-- Enlace al lado derecho -->
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link" href="/logout">Cerrar Sesión</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <h1 class="ms-3">Bancos</h1>
    <!-- Botón para agregar un nuevo banco -->
    <a href="/bancos/add"><button class="btn btn-primary ms-3">Agregar Banco</button></a>

    <br /><br />

    <!-- Tabla de bancos -->
    <table class="table table-dark table-striped">
      <thead>
        <tr class="text-center">
          <th scope="col">ID</th>
          <th scope="col">Rut</th>
          <th scope="col">Nombre</th>
          <th scope="col">Fono Movil</th>
          <th scope="col">Email</th>
          <th scope="col">Acciones</th>
        </tr>
      </thead>
      <tbody>
        {% for banco in bancos %}
        <tr class="text-center">
          <td>{{ banco[0] }}</td>
          <td>{{ banco[1] }}</td>
          <td>{{ banco[2] }}</td>
          <td>{{ banco[3] }}</td>
          <td>{{ banco[4] }}</td>
          <td>
            <!-- Botón para editar -->
            <a href="/bancos/edit/{{ banco[0] }}"><button class="btn btn-warning">Editar</button></a>

            <!-- Botón para eliminar -->
            <form
              action="{{ url_for('bancos_bp.delete_banco', id_banco=banco[0]) }}"
              method="POST"
              style="display: inline"
              onsubmit="return confirm('¿Estás seguro de que deseas eliminar este banco?');"
            >
              <button type="submit" class="btn btn-danger">
                Eliminar
              </button>
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <br />
    <a href="/"><button class="btn btn-primary ms-3">Volver al Inicio</button></a>
  </body>
</html>

templates/configuracion/bancos/edit_banco.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Editar Banco</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles.css') }}"
    />
  </head>
  <body class="centered-form">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Sistema de Inversiones</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto">
            <!-- Menú Desplegable -->
            <li class="nav-item dropdown mx-3">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Ingresos
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/bancos">Bancos</a></li>
                <li><a class="dropdown-item" href="/empresas">Empresas</a></li>
                <li><a class="dropdown-item" href="/corredores">Corredores de Bolsa</a></li>
                <li><a class="dropdown-item" href="/companias">Compañías de Seguro</a></li>
                <li><a class="dropdown-item" href="/clientes">Clientes</a></li>
                <li><a class="dropdown-item" href="/parametros">Parámetros</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown mx-3">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Inversiones
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/acciones">Acciones</a></li>
                <li><a class="dropdown-item" href="/fondos_mutuos">FFMM</a></li>
                <li><a class="dropdown-item" href="/deposito_a_plazo">DP</a></li>
              </ul>
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link" href="/boletas_garantia"
                >Boletas de Garantia</a
              >
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link" href="/polizas">Polizas de Seguro</a>
            </li>
          </ul>
          <!-- Enlace al lado derecho -->
          </ul>
          <!-- Enlace al lado derecho -->
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link" href="/logout">Cerrar Sesión</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <form
      action="{{ url_for('bancos_bp.edit_banco', id_banco=id_banco) }}"
      method="POST"
    >
      <h1>Editar Banco</h1>
      <label for="rut">Rut:</label>
      <input
        type="text"
        id="rut"
        name="rut"
        value="{{ banco[0] }}"
        required
      /><br /><br />

      <label for="nombre">Nombre:</label>
      <input
        type="text"
        id="nombre"
        name="nombre"
        value="{{ banco[1] }}"
        required
      /><br /><br />

      <label for="email">Email:</label>
      <input
        type="email"
        id="email"
        name="email"
        value="{{ banco[2] }}"
      /><br /><br />

      <label for="fono_fijo">Fono Fijo:</label>
      <input
        type="text"
        id="fono_fijo"
        name="fono_fijo"
        value="{{ banco[3] }}"
      /><br /><br />

      <label for="fono_movil">Fono Móvil:</label>
      <input
        type="text"
        id="fono_movil"
        name="fono_movil"
        value="{{ banco[4] }}"
      /><br /><br />

      <button type="submit">Guardar Cambios</button>
      <button type="button" onclick="location.href='/bancos'">Volver</button>
    </form>
  </body>
</html>