blueprints/companias.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify
from flask_login import login_required 
from database import get_db_connection

companias_bp = Blueprint('companias_bp', __name__)

@companias_bp.route('/companias', methods=['GET'])
@login_required
def listar_companias():
    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        cursor.execute("""
            SELECT ID_Entidad, Rut, Nombre, FonoMovil, Email
            FROM Entidad
            WHERE TipoEntidad = 'Compania'
            ORDER BY Nombre ASC
            """)
        companias = cursor.fetchall()

    except Exception as e:
        flash(f"Error al obtener los datos de los companias: {e}", "error")
        companias = []

    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

    return render_template('configuracion/companias/companias.html', companias=companias)

@companias_bp.route('/companias/add', methods=['GET', 'POST'])
@login_required
def add_compania():
    if request.method == 'POST':
        rut = request.form['rut']
        nombre = request.form['nombre'].upper()
        email = request.form.get('email')  
        fono_fijo = request.form.get('fono_fijo')  
        fono_movil = request.form.get('fono_movil')  

        try:
            conn = get_db_connection()
            cursor = conn.cursor()

            cursor.execute("""
                INSERT INTO Entidad (Rut, Nombre, Email, FonoFijo, FonoMovil, TipoEntidad)
                VALUES (%s, %s, %s, %s, %s, 'Compania')
            """, (rut, nombre, email, fono_fijo, fono_movil))
            conn.commit()

            flash("Compania agregado exitosamente.", "success")
            return redirect(url_for('companias_bp.listar_companias'))
        except Exception as e:
            conn.rollback()
            flash(f"Error al agregar el compania: {e}", "error")
        finally:
            cursor.close()
            conn.close()

    return render_template('configuracion/companias/add_companias.html')

@companias_bp.route('/delete_compania/<int:id_compania>', methods=['POST'])
@login_required
def delete_compania(id_compania):
    print(f"Entrando a delete_compania con ID: {id_compania}")
    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        cursor.execute("SELECT * FROM Entidad WHERE ID_Entidad = %s AND TipoEntidad = 'Compania'", (id_compania,))
        compania = cursor.fetchone()
        if not compania:
            flash("El compania no existe o no es del tipo 'Compania'.", "error")
            return redirect(url_for('companias_bp.listar_companias'))

        cursor.execute("DELETE FROM Entidad WHERE ID_Entidad = %s AND TipoEntidad = 'Compania'", (id_compania,))
        conn.commit()

        print(f"Compania eliminado: {id_compania}")
        flash("Compania eliminado exitosamente.", "success")
    except Exception as e:
        conn.rollback()
        print(f"Error al eliminar: {e}")
        flash(f"Error al eliminar el compania: {e}", "error")
    finally:
        cursor.close()
        conn.close()

    return redirect(url_for('companias_bp.listar_companias'))

@companias_bp.route('/companias/edit/<int:id_compania>', methods=['GET', 'POST'])
@login_required
def edit_compania(id_compania):
    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        if request.method == 'POST':
            rut = request.form['rut']
            nombre = request.form['nombre']
            email = request.form.get('email')  
            fono_fijo = request.form.get('fono_fijo')  
            fono_movil = request.form.get('fono_movil')  

            cursor.execute("""
                UPDATE Entidad
                SET Rut = %s, Nombre = %s, Email = %s, FonoFijo = %s, FonoMovil = %s
                WHERE ID_Entidad = %s AND TipoEntidad = 'Compania'
            """, (rut, nombre, email, fono_fijo, fono_movil, id_compania))
            conn.commit()

            flash("Compania actualizado exitosamente.", "success")
            return redirect(url_for('companias_bp.listar_companias'))

        cursor.execute("""
            SELECT Rut, Nombre, Email, FonoFijo, FonoMovil
            FROM Entidad
            WHERE ID_Entidad = %s AND TipoEntidad = 'Compania'
        """, (id_compania,))
        compania = cursor.fetchone()

        if not compania:
            flash("Compania no encontrado.", "error")
            return redirect(url_for('companias_bp.listar_companias'))

    except Exception as e:
        if conn:
            conn.rollback()
        flash(f"Error al procesar la solicitud: {e}", "error")
        return redirect(url_for('companias_bp.listar_companias'))
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

    return render_template('configuracion/companias/edit_companias.html', compania=compania, id_compania=id_compania)

templates/configuracion/companias/add_companias.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Agregar Compañia</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles.css') }}"
    />
  </head>
  <body class="centered-form">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Sistema de Inversiones</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto">
            <!-- Menú Desplegable -->
            <li class="nav-item dropdown mx-3">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Ingresos
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/bancos">Bancos</a></li>
                <li><a class="dropdown-item" href="/empresas">Empresas</a></li>
                <li><a class="dropdown-item" href="/corredores">Corredores de Bolsa</a></li>
                <li><a class="dropdown-item" href="/companias">Compañías de Seguro</a></li>
                <li><a class="dropdown-item" href="/clientes">Clientes</a></li>
                <li><a class="dropdown-item" href="/parametros">Parámetros</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown mx-3">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Inversiones
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/acciones">Acciones</a></li>
                <li><a class="dropdown-item" href="/fondos_mutuos">FFMM</a></li>
                <li><a class="dropdown-item" href="/deposito_a_plazo">DP</a></li>
              </ul>
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link" href="/boletas_garantia"
                >Boletas de Garantia</a
              >
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link" href="/polizas">Polizas de Seguro</a>
            </li>
          </ul>
          <!-- Enlace al lado derecho -->
          </ul>
          <!-- Enlace al lado derecho -->
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link" href="/logout">Cerrar Sesión</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <form action="{{ url_for('companias_bp.add_compania') }}" method="POST">
      <h1>Agregar Compañia</h1>
      <label for="rut">Rut:</label>
      <input
        type="text"
        id="rut"
        name="rut"
        oninput="this.value = this.value.replace(/[^0-9]/g, '');"
        required
      /><br /><br />

      <label for="nombre">Nombre:</label>
      <input
        type="text"
        id="nombre"
        name="nombre"
        oninput="this.value = this.value.toUpperCase()"
        required
      /><br /><br />

      <label for="email">Email:</label>
      <input type="email" id="email" name="email" /><br /><br />

      <label for="fono_fijo">Fono Fijo:</label>
      <input
        type="text"
        id="fono_fijo"
        name="fono_fijo"
        oninput="this.value = this.value.replace(/[^0-9]/g, '');"
      /><br /><br />

      <label for="fono_movil">Fono Móvil:</label>
      <input
        type="text"
        id="fono_movil"
        name="fono_movil"
        oninput="this.value = this.value.replace(/[^0-9]/g, '');"
      /><br /><br />

      <button type="submit">Guardar</button>
      <button onclick="location.href='/companias'" type="button">Volver</button>
    </form>
  </body>
</html>

templates/configuracion/companias/companias.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Compañias De Seguro</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      rel="stylesheet"
    />
    <link
      rel="icon"
      href="{{ url_for('static', filename='images/favicon.png') }}"
      type="image/x-icon"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      defer
    ></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Sistema de Inversiones</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto">
            <!-- Menú Desplegable -->
            <li class="nav-item dropdown mx-3">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Ingresos
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/bancos">Bancos</a></li>
                <li><a class="dropdown-item" href="/empresas">Empresas</a></li>
                <li><a class="dropdown-item" href="/corredores">Corredores de Bolsa</a></li>
                <li><a class="dropdown-item" href="/companias">Compañías de Seguro</a></li>
                <li><a class="dropdown-item" href="/clientes">Clientes</a></li>
                <li><a class="dropdown-item" href="/parametros">Parámetros</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown mx-3">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Inversiones
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/acciones">Acciones</a></li>
                <li><a class="dropdown-item" href="/fondos_mutuos">FFMM</a></li>
                <li><a class="dropdown-item" href="/deposito_a_plazo">DP</a></li>
              </ul>
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link" href="/boletas_garantia"
                >Boletas de Garantia</a
              >
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link" href="/polizas">Polizas de Seguro</a>
            </li>
          </ul>
          <!-- Enlace al lado derecho -->
          </ul>
          <!-- Enlace al lado derecho -->
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link" href="/logout">Cerrar Sesión</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <h1 class="ms-3">Compañias De Seguro</h1>

    <!-- Botón para agregar un nuevo compania -->
    <a href="/companias/add"><button class="btn btn-primary ms-3">Agregar Compañia</button></a>

    <br /><br />

    <!-- Tabla de companias -->
    <table class="table table-dark table-striped">
      <thead>
        <tr class="text-center">
          <th scope="col">ID</th>
          <th scope="col">Rut</th>
          <th scope="col">Nombre</th>
          <th scope="col">Fono Movil</th>
          <th scope="col">Email</th>
          <th scope="col">Acciones</th>
        </tr>
      </thead>
      <tbody>
        {% for compania in companias %}
        <tr class="text-center">
          <td>{{ compania[0] }}</td>
          <td>{{ compania[1] }}</td>
          <td>{{ compania[2] }}</td>
          <td>{{ compania[3] }}</td>
          <td>{{ compania[4] }}</td>
          <td>
            <!-- Botón para editar -->
            <a href="/companias/edit/{{ compania[0] }}"
              ><button class="btn btn-warning">Editar</button></a
            >

            <!-- Botón para eliminar -->
            <form
              action="{{ url_for('companias_bp.delete_compania', id_compania=compania[0]) }}"
              method="POST"
              style="display: inline"
              onsubmit="return confirm('¿Estás seguro de que deseas eliminar esta compañia?');"
            >
              <button type="submit" class="btn btn-danger">
                Eliminar
              </button>
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <br />
    <a href="/"><button class="btn btn-primary ms-3">Volver al Inicio</button></a>
  </body>
</html>

templates/configuracion/companias/edit_companias.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Editar Compañia</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles.css') }}"
    />
  </head>
  <body class="centered-form">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Sistema de Inversiones</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto">
            <!-- Menú Desplegable -->
            <li class="nav-item dropdown mx-3">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Ingresos
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/bancos">Bancos</a></li>
                <li><a class="dropdown-item" href="/empresas">Empresas</a></li>
                <li><a class="dropdown-item" href="/corredores">Corredores de Bolsa</a></li>
                <li><a class="dropdown-item" href="/companias">Compañías de Seguro</a></li>
                <li><a class="dropdown-item" href="/clientes">Clientes</a></li>
                <li><a class="dropdown-item" href="/parametros">Parámetros</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown mx-3">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Inversiones
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/acciones">Acciones</a></li>
                <li><a class="dropdown-item" href="/fondos_mutuos">FFMM</a></li>
                <li><a class="dropdown-item" href="/deposito_a_plazo">DP</a></li>
              </ul>
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link" href="/boletas_garantia"
                >Boletas de Garantia</a
              >
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link" href="/polizas">Polizas de Seguro</a>
            </li>
          </ul>
          <!-- Enlace al lado derecho -->
          </ul>
          <!-- Enlace al lado derecho -->
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link" href="/logout">Cerrar Sesión</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <form
      action="{{ url_for('companias_bp.edit_compania', id_compania=id_compania) }}"
      method="POST"
    >
      <h1>Editar Compañia</h1>
      <label for="rut">Rut:</label>
      <input
        type="text"
        id="rut"
        name="rut"
        value="{{ compania[0] }}"
        required
      /><br /><br />

      <label for="nombre">Nombre:</label>
      <input
        type="text"
        id="nombre"
        name="nombre"
        value="{{ compania[1] }}"
        required
      /><br /><br />

      <label for="email">Email:</label>
      <input
        type="email"
        id="email"
        name="email"
        value="{{ compania[2] }}"
      /><br /><br />

      <label for="fono_fijo">Fono Fijo:</label>
      <input
        type="text"
        id="fono_fijo"
        name="fono_fijo"
        value="{{ compania[3] }}"
      /><br /><br />

      <label for="fono_movil">Fono Móvil:</label>
      <input
        type="text"
        id="fono_movil"
        name="fono_movil"
        value="{{ compania[4] }}"
      /><br /><br />

      <button type="submit">Guardar Cambios</button>
      <button type="button" onclick="location.href='/companias'">Volver</button>
    </form>
  </body>
</html>